logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG
servlet:

      multipart:
        max-file-size: 1MB
        max-request-size: 5MB
        enabled: true
cloudinary:
    api_key: 574976897654358
    api_secret: "${cloudinary_secret}"
    cloud_name: dr3m6za90
server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    # Put here your user name
    username: root
    # Put here your password
    password: memento
    url: jdbc:mysql://localhost:3306/fun_vinyl?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    #For MySQL 8 uncomment bellow (comment MySQL 5)
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5 (innodb dialect below)
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true